# Absolute tracking parameters for SonarCloud Cloud UI
sonar.organization=rajeshpandi2325
sonar.projectKey=rajeshpandi2325_enterprise-core-application
sonar.projectName=enterprise-core-application

# Path to the source code to be scanned
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/build/**,**/public/**

# Encoding of the source code files
sonar.sourceEncoding=UTF-8
